tags:
  - Tasks
summary: Update task
operationId: updateTask
description: Update an existing task by its ID. Only the user who created the task (userId) can update it.
security:
  - bearerAuth: []
parameters:
  - in: path
    name: taskId
    required: true
    schema:
      type: string
      example: '65ca67e7ae7f10c88b598384'
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          name:
            type: string
            description: Task title
            example: Prepare September report
          date:
            type: string
            description: Date in format YYYY.MM.DD (other formats are not supported)
            example: '2025.09.20'
responses:
  '200':
    description: Successfully updated a task
    content:
      application/json:
        schema:
          type: object
          required:
            - status
            - message
            - data
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Successfully updated a task!
            data:
              $ref: ../../../components/schemas/task.yaml
  '401':
    $ref: '../../../components/responses/401.yaml'
  '400':
    $ref: '../../../components/responses/400.yaml'
  '404':
    $ref: '../../../components/responses/404.yaml'
