tags:
  - Tasks
summary: Toggle the status of a task
description: Toggles the `isDone` field of a task.
operationId: toggleTaskStatus
security:
  - bearerAuth: []

parameters:
  - name: taskId
    in: path
    required: true
    description: The ID of the task to update
    schema:
      type: string
      example: '650f7f5d4a1c2b00123abcd1'

responses:
  '200':
    description: Task status updated successfully
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Task status updated successfully
            data:
              $ref: '../../../../components/schemas/task.yaml'
  '400':
    $ref: '../../../../components/responses/400.yaml'
  '401':
    $ref: '../../../../components/responses/401.yaml'
  '500':
    $ref: '../../../../components/responses/500.yaml'
