openapi: 3.1.0
info:
  version: 1.0.0
  title: MomJourney API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing tasks, diaries, users, and authentication for the MomJourney app.
tags:
  - name: Auth
    description: Operations for user registration, login, and authentication management.
  - name: Diaries
    description: Operations for managing diaries.
  - name: Tasks
    description: Operations for managing tasks.
  - name: Users
    description: Operations for managing user profiles.
  - name: Weeks
    description: Operations related to weekly plans or summaries.
  - name: Emotions
    description: Operations for managing emotions
servers:
  - url: https://beckend-project-stork.onrender.com
paths:
  /api/emotions:
    get:
      $ref: ../swagger/paths/emotions/get.yaml

  /api/users:
    get:
      $ref: ../swagger/paths/users/get.yaml
    patch:
      $ref: ../swagger/paths/users/patch.yaml

  /api/users/avatar:
    patch:
      $ref: ../swagger/paths/users/avatar/put.yaml

  /api/auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml

  /api/auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml

  /api/auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml

  /api/auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml

  /api/diaries:
    get:
      $ref: ../swagger/paths/diaries/get.yaml
    post:
      $ref: ../swagger/paths/diaries/post.yaml

  /api/diaries/{diaryId}:
    patch:
      $ref: ../swagger/paths/diaries/{diaryId}/patch.yaml
    delete:
      $ref: ../swagger/paths/diaries/{diaryId}/delete.yaml
    get:
      $ref: ../swagger/paths/diaries/{diaryId}/get.yaml

  /api/tasks:
    get:
      $ref: ../swagger/paths/tasks/get.yaml
    post:
      $ref: ../swagger/paths/tasks/post.yaml

  /api/tasks/{taskId}:
    patch:
      $ref: ../swagger/paths/tasks/{taskId}/patch.yaml

  /api/tasks/{taskId}/status:
    patch:
      $ref: ../swagger/paths/tasks/{taskId}/status/patch.yaml

  /api/weeks/public:
    get:
      $ref: ../swagger/paths/weeks/getPublicWeek.yaml
  /api/weeks/private:
    get:
      $ref: ../swagger/paths/weeks/getPrivateWeeks.yaml

  /api/weeks/mom-state/{week}:
    get:
      $ref: ../swagger/paths/weeks/{week}/getMomStates.yaml

  /api/weeks/baby-state/{week}:
    get:
      $ref: ../swagger/paths/weeks/{week}/getBabyStates.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
