openapi: 3.1.0
info:
  version: 1.0.0
  title: MomJourney API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: API for managing tasks, diaries, users, and authentication for the MomJourney app.
tags:
  - name: Auth
    description: Operations for user registration, login, and authentication management.
  - name: Diaries
    description: Operations for managing diaries.
  - name: Tasks
    description: Operations for managing tasks.
  - name: Users
    description: Operations for managing user profiles.
  - name: Week
    description: Operations related to weekly plans or summaries.
  - name: Emotions
    description: Operations for managing emotions
servers:
  - url: http://localhost:3000
  # - url: https://nodejs-hw-mongodb-c3yu.onrender.com
paths:
  /api/emotions:
    get:
      $ref: ../swagger/paths/emotions/get.yaml
      
  /api/users:
    get: 
      $ref: ../swagger/paths/users/getUser.yaml   
      
  /api/users/avatar:
    put:
      $ref: ../swagger/paths/users/updateAvatar.yaml

  /api/auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml

  /api/auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
      
  /api/auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml

  /api/diaries/{diaryId}:
    patch:
      $ref: ../swagger/paths/diaries/{diaryId}/patch.yaml

  /api/diaries:
    get:
      $ref: ../swagger/paths/diaries/get.yaml

  /api/tasks:
    post:
      $ref: ../swagger/paths/tasks/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
