tags:
  - Tasks
summary: Get all tasks
description: >
  Private endpoint to get all tasks.  
  Returns tasks sorted by `date` in ascending order by default.

operationId: getAllTasks
security:
  - bearerAuth: []

parameters:
  - in: query
    name: isDone
    required: false
    schema:
      type: boolean
    description: >
      Optional filter by completion status.  
      When omitted, returns both completed and uncompleted tasks.
    examples:
      all:
        summary: All tasks
        value: null
      onlyCompleted:
        summary: Only completed tasks
        value: true
      onlyUncompleted:
        summary: Only uncompleted tasks
        value: false

  - in: query
    name: order
    required: false
    schema:
      type: string
      enum: [asc, desc]
      default: asc
    description: >
      Sort order by `date`.  
      - `asc` = ascending (default)  
      - `desc` = descending
    examples:
      ascending:
        summary: Ascending
        value: asc
      descending:
        summary: Descending
        value: desc

responses:
  '200':
    description: List of tasks sorted by date
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Tasks fetched successfully
            data:
              type: array
              items:
                $ref: '../../components/schemas/task.yaml'
  '400':
    $ref: '../../components/responses/400.yaml'
  '401':
    $ref: '../../components/responses/401.yaml'
  '500':
    $ref: '../../components/responses/500.yaml'
