paths:
  /tasks/{id}/status:
    patch:
      tags:
        - Tasks
      summary: Toggle the status of a task
      description: Toggles the `isDone` field of a task.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: string
            example: '650f7f5d4a1c2b00123abcd1'
      requestBody:
        description: Optional request body (empty, since toggle is automatic)
        required: false
        content:
          application/json:
            schema:
              type: object
              example: {}
      responses:
        '200':
          description: Task status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 'Task status updated successfully'
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: '650f7f5d4a1c2b00123abcd1'
                      name:
                        type: string
                        example: 'Test Task'
                      date:
                        type: string
                        example: '2025-09-17'
                      isDone:
                        type: boolean
                        example: true
                      userId:
                        type: string
                        example: '650f7f5d4a1c2b00123abcf'
                      createdAt:
                        type: string
                        format: date-time
                        example: '2025-09-17T10:00:00.000Z'
                      updatedAt:
                        type: string
                        format: date-time
                        example: '2025-09-17T12:00:00.000Z'
        '404':
          $ref: '#/components/responses/404.yaml'
        '401':
          $ref: '#/components/responses/401.yaml'
