tags:
  - Tasks
summary: createTask
description: Private endpoint to create a new task.
operationId: createTask
security:
  - bearerAuth: []

requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        required:
          - name
          - date
        properties:
          name:
            type: string
            example: 'Buy milk'
            description: The name of the task
          date:
            type: string
            example: '19.09.2025'
            description: Date in format DD.MM.YYYY
            pattern: '^\d{2}\.\d{2}\.\d{4}$'
          isDone:
            type: boolean
            example: false
            description: Task completion status

responses:
  '201':
    description: Task created successfully
    content:
      application/json:
        schema:
          type: object
          required:
            - status
            - message
            - data
          properties:
            status:
              type: integer
              example: 201
            message:
              type: string
              example: Successfully created a task!
            data:
              $ref: '../../components/schemas/task.yaml'
  '400':
    $ref: '../../components/responses/400.yaml'
  '401':
    $ref: '../../components/responses/401.yaml'
  '500':
    $ref: '../../components/responses/500.yaml'
